### ISSUE TITLE
[UI] Enable sub-links for settings sub-tabs

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery#1150]
**Description**

Right now the URL of the subtabs in settings are distinguished by `/settings#name_of_tab` which is cause of many bugs right now.

**Expected Behavior**

Have a anchor sub-URL for each tab like `settings/name_of_tab`.

**Comment by leecalcote** [comment]
Oooh, @Nikhil-Ladha... Calling @Nikhil-Ladha... 😄

**Comment by Nikhil-Ladha** [comment]
Here I am @leecalcote 👀.

**Comment by Nikhil-Ladha** [comment]
Will look into it, over the weekend 😉.

**Comment by kushthedude** [comment]
Please @Nikhil-Ladha !

**Comment by leecalcote** [comment]
Do we anticipate this issue to be address simultaneously or is its root cause distinct? https://github.com/meshery/meshery/issues/273

**Comment by leecalcote** [comment]
Related to #967

**Comment by Nikhil-Ladha** [comment]
> Do we anticipate this issue to be address simultaneously or is its root cause distinct? #273

Not sure, will have to check.

**Comment by Nikhil-Ladha** [comment]
If I may ask @kushthedude , what is the issue with the current anchor? Because the '#name_of_tab' makes sense here, considering these are subparts within a page if we use '/name_of_tab' that indicates a new page adding in the route.

**Comment by Nikhil-Ladha** [comment]
If I am correct, the issue that you are saying are two of them:

- On submitting the preferences in the performance tab the page reloads back to the environment tab rather than staying on the same one.

- On initial rendering of the settings page, the path is just settings, rather it should be having the '#environment' sub link added to it.

Are these the issues you are talking about?
