### ISSUE TITLE
Move common codes in the adapters to a separate repo and make it a lib (to reduce duplication)

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#131]
We now have several adapters: Istio, Linkerd, consul, etc.
The three adapters have some common code which could be moved to a common repo and update the adapters to use the common code from the library.

**Comment by PluckyPrecious** [comment]
Knock Knock! @leecalcote @girishranganathan checking in for situation report.😃

**Comment by leecalcote** [comment]
There has been movement on this issue with @kumarabd preparing a standard kit to be used in the refactoring of adapters. However, this issue remains largely unaddressed.

**Comment by Maxgit3** [comment]
@leecalcote is there any assistance I can provide with this?

**Comment by leecalcote** [comment]
Hi @Maxgit3, thank you for asking about this issue. As it turns out we are tardy on closing this particular one. It was taken care of when MeshKit and the Meshery Adapter Library were created. All the the Meshery Adapters have been rewritten now to make use of these libraries. 

There are a number of other open issues that might be of interest to you. Is golang your focus?
