### ISSUE TITLE
Rename SMPS project to SMP

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1379]
**Current State:**
This project is undergoing a name change in which it will drop the "S"

**Comment by leecalcote** [comment]
@JubayerJoy, I'm not sure if this is completed for the `meshery` repo and its docs or not...

**Comment by JubayerJoy** [comment]
Hi @leecalcote, I have checked the whole meshery site, repo, and docs. I just found only one issue, everything else seems really good 👍 
I will open a PR to fix this.

<img src ="https://imgur.com/OE9mZeQ.png">
While screening, I have noticed some issues #1357 

I have also found an issue in the Layer5.io footer section, that needs to fixed in that repo. I will try to look into that repo as well for similar issues. 

<img src= "https://imgur.com/zkR0ggC.png">

Hope that covers it 😃

**Comment by leecalcote** [comment]
Thank you, @JubayerJoy. There's one more on the layer5.io site at layer5.io/meshery - - 
<img width="562" alt="Screen Shot 2020-08-13 at 9 33 33 PM" src="https://user-images.githubusercontent.com/7570704/90207750-b17b9080-ddac-11ea-908e-965d8ae09eb0.png">

The latest SMP logos are available in the Layer5 Sites drive.
