### ISSUE TITLE
[UI] Enhance indication of enabled vs disabled in user preferences interface

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1470]
**Current Behavior**
The current version of the user preferences UI looks like this:

<img width="1321" alt="Screen Shot 2020-08-27 at 12 41 21 PM" src="https://user-images.githubusercontent.com/7570704/91476596-cfdc9400-e862-11ea-8d56-b3330da24637.png">

It's difficult to tell which way is on and which way is off. 

The toaster notification is of no help in this regard either:

<img width="370" alt="Screen Shot 2020-08-27 at 12 43 18 PM" src="https://user-images.githubusercontent.com/7570704/91476733-ff8b9c00-e862-11ea-8f35-1df429693136.png">

**Desired Behavior**
1. Whether a given setting is enabled or disabled should be obvious to the user just looking at the page.
1. When the user changes the setting, the notification message should indicate enabled or disabled.

**Implementation**
1. Update UI to make it intuitive to distinguish on vs off for a given setting.
1.  Update the text in the notification to indicate enabled vs disabled.
1. Add the label "Analytics and Improvement Program" as a group label around both of these options, ideally, in a format like this:
<img width="358" alt="Screen Shot 2020-08-27 at 12 49 54 PM" src="https://user-images.githubusercontent.com/7570704/91477377-e46d5c00-e863-11ea-9e30-ed806337602d.png">

**Acceptance Tests**
1. Sending of usage statistics should be enabled by default.
1. Users should be able to understand whether a preference is enabled or disabled without having to take any action.
1. "enabled" and "disabled" should show in the notification text.
1. These two settings are grouped under a label (of some kind).

**Comment by alabobriggs** [comment]
I will like to work on this

**Comment by PluckyPrecious** [comment]
Hi @alabobriggs how is this coming up?😊

**Comment by alabobriggs** [comment]
Hello @PluckyPrecious still working on it. Had some challenges earlier

**Comment by shubhamgupta2956** [comment]
Hi everyone, I want to take this issue. Please assign it to me.

**Comment by leecalcote** [comment]
@shubhamgupta2956 checking on progress... how are you coming along here?

**Comment by Nikhil-Ladha** [comment]
@shubhamgupta2956  if you are not working on this, can I take it up?

**Comment by shubhamgupta2956** [comment]
Sorry for the late reply. I was a bit busy with my college assignment (I hope I can complete it till this weekend) so could not complete it. @leecalcote, I have experimented the mentioned things with this page but some of them does not look much elegant due to:-
* Group label - Embedding these settings in the format provided feels different from the app themes. I 
* Also I could not find anything better to make it intuitive to distinguish on vs off for a given setting. If I change any color then it does not goes with the whole app theme. Apart from this, I am not much in favor of removing the current on/off component as this looks minimalistic and works great for this use case.

@Nikhil-Ladha sure you can take this issue. Feel free to ask for any help if required. :slightly_smiling_face:

**Comment by Nikhil-Ladha** [comment]
If you are done with your exams and hoping to work on it this weekend, then please feel free to do it. 
I just wanted to make some PRs for hacktoberfest 😆

**Comment by shubhamgupta2956** [comment]
If you got any good ideas for the above-mentioned problems, it would be better if you implement it. We can also discuss the ways to implement this after this weekend on slack also.

**Comment by Nikhil-Ladha** [comment]
Okay, then. I ahve some thoughts and will make a PR soon🙂.
Will rag you there too, to have a look.
