### ISSUE TITLE
Change the ports for meshery-osm adaptor 

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery#1547]

**Comment by leecalcote** [comment]
The Meshery Adapter for Open Service Mesh network port needs to be assigned to 10009. Update [Meshery Docs](https://github.com/meshery/meshery/tree/master/docs) so that the reserved network port documentation reflects use of port 10009 - https://meshery.meshery.io/docs/architecture#network-ports

@KarenEfereyan, since you'll be in this page in the docs anyway, you're welcome to make this update as well, if you like.

**Comment by KarenEfereyan** [comment]
Sure @leecalcote will do

**Comment by kumarabd** [comment]
Thanks @KarenEfereyan . Let me know if you need some help on this.

**Comment by KarenEfereyan** [comment]
@kumarabd ill do this right now. Im so sorry ive been ill. The reason for the delay. I'll get to it right now

**Comment by ghost** [comment]
Hi @leecalcote and @kumarabd sorry for the delay. There has been no light at my end all day. Im so sorry. But then,I cannot seem to find this [file](https://meshery.meshery.io/docs/architecture#network-ports)  in the meshery project opened in my editor. I already pulled the latest changes from meshery. Am i doing something wrong?

**Comment by leecalcote** [comment]
Here's a link - https://github.com/meshery/meshery/blob/master/docs/pages/architecture.md

**Comment by ghost** [comment]
> Here's a link - https://github.com/meshery/meshery/blob/master/docs/pages/architecture.md

Thank you
