### ISSUE TITLE
[UI]: Unexpected error popping up for 'View SMI Conformance Results'

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/meshery#1631]
**Description**

On navigating to any of the adapter page and without performing any SMI Conformance test, on clicking the `View SMI Conformance Result` chip a modal opens showing the empty table. But, just within a minute an error snackbar pops consuming the whole page (see in the screenshot below)

**Expected Behavior**

The snackbar should not come up even if no tests have been run.

**Screenshots**

![Screenshot from 2020-10-02 16-27-42](https://user-images.githubusercontent.com/29438875/94925275-94298f80-04dc-11eb-9446-a77bef7bb223.png)

**Environment:**
 - OS: [e.g. Ubuntu]: Fedora 32
 - Browser: [e.g. Chrome, Safari] Chrome
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8] Laptop

---
[Optional] **To Reproduce**
1. Go to '...' Adapters page
2. Click on '....' View SMI Conformance Results chip
3. See error snackbar pop up within few moments

[Optional] **Additional Context**

**Comment by Nikhil-Ladha** [comment]
@dhruv0000 , @kumarabd , @leecalcote ^^

**Comment by KarenEfereyan** [comment]
What could be the cause of the error? I would like to reproduce the error but my system's bad right now😫😫

**Comment by kumarabd** [comment]
@Nikhil-Ladha Which service mesh gave u this?

**Comment by Nikhil-Ladha** [comment]
All of them

> @Nikhil-Ladha Which service mesh gave u this?

**Comment by dhruv0000** [comment]
Seems like problem is logging in with meshery provider for the movement, since we have not implemented the provider database endpoint for fetching SMI results.
Since we have two visual conformation of data not getting fetched (the table itself and the snackbar ), you are right @Nikhil-Ladha , There is no need of the snackbar to be shown in case of data not getting fetched since the table already shows "Sorry, no matching records found" in that case.
