### ISSUE TITLE
[mesheryctl]: Fetching Server Version not successful 

### ISSUE THREAD

**Issue by NupurThakur27** [layer5io/meshery#1660]
**Description**
The api that provides the server version goes missing sometimes.

**Expected Behavior**

If the `api/server/version` doesn't return anything or isn't available it should show a proper message or error regarding that.

**Screenshots**

![Screenshot from 2020-10-03 12-03-27](https://user-images.githubusercontent.com/39610703/95342246-dab02d00-08d4-11eb-96d1-9e9e2a721027.png)

**Environment:**
 - OS: Ubuntu
 - Version: 18.04
 - Device: laptop

**Comment by anirudhjain75** [comment]
Hi @NupurThakur27, This is due to deployment of faulty server. 
<img width="784" alt="image" src="https://user-images.githubusercontent.com/14249589/95352730-22888180-08e0-11eb-9518-b0375520cf0a.png">
This is the status of latest master, try running `make run-local` to run meshery server instead of deployed version.
