### ISSUE TITLE
[Docs] Internationalization and localization of Meshery Docs (i18n compatible)

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1789]
**Current State:**
Meshery documentation is being translated to other languages than English. 

**Desired State:**
Incorporate the https://github.com/kurtsson/jekyll-multiple-languages-plugin plugin into Meshery's documentation system.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by chandrashritii** [comment]
@jesuslerma Want to take this up?

**Comment by leecalcote** [comment]
Progress! - https://meshery.layer5.io/docs/es. 

// @jlcastrogro @edwvilla @rubenlorenzo @chaltenio @jesuslerma @alonsolopezr @Drake8710 @jeojhx @ramrodo

**Comment by leecalcote** [comment]
@jesuslerma @chandrashritii ETA?

**Comment by leecalcote** [comment]
@jesuslerma @chandrashritii @alonsolopezr should this issue be reopened? Is this something that you'll complete?

**Comment by leecalcote** [comment]
> @jesuslerma @chandrashritii @alonsolopezr should this issue be reopened? Is this something that you'll complete?

Are we tossing in the towel here?

**Comment by jesuslerma** [comment]
At the las CI meeting, I think that @alonsolopezr was having a meeting with @chandrashritii  let me ask how the meeting was on. Anyway, when I tried the plugin it wasn't easy to adapt to our current structure, maybe because I'm not a Jekyll expert, or maybe because the plugin needs another stuff to work. IDK. If that plugin doesn't work, maybe we can check the options we have:
- Create our own way to do the translations (we already have the permalink structure in fact).
- Create our own way to automatically add a button to switch between languages on each page. I think there is the only part that we are missing now.

**Comment by alonsolopezr** [comment]
@leecalcote I'm getting all ready to make a PR about it just now... I was at a very low pace beacause of trying the jekyll plugin to work ( just wasted a couple of weeks)
I started from a boilerplate of another jekyll code base, from a presentation about it, I saw on youtube... 
SO that's done..
Now I resolved in these last days, instructed by @chandrashritii, to have the same pages/* files for the es/ and tr/ languages. Done.
Resolved the sidebar links, to be displayed on the language selected. Done.
Resolved the index.md of the language selected, to be display in the language selected, (front matter stuff from each lang file), done...

So I was hoping to have a meet today with @chandrashritii, but I think in the mean time I could get all this in a PR, for validation? would this be ok?
Thanks in advance
