### ISSUE TITLE
Performance: M4: Expose Load Generator settings in UI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#213]
**Description**
See #126 for full description of Load Generator Integration Epic. Selection of load generator should be made available in two locations:

1. as a general setting under the /settings screen. This setting will be the default for all performance tests.
1. as a per test setting under the /performance screen. This setting will be one-time for _that_ specific test.

**M4: Expose Load Generator settings in UI**
- [x] Per test selection under /performance: Update UI to select from the choice of load generators (fortio and wrk2) and include it as part of the payload to submit a job for load test, fetch response and process it the usual way. See mockup:

<img width="1548" alt="Screen Shot 2019-09-24 at 4 23 05 PM" src="https://user-images.githubusercontent.com/7570704/65551983-cb885800-dee8-11e9-9c73-66001d3f55c3.png">

- [ ] Default selection under /settings: Add load generators as a new section in the Settings screen. Fortio will be the default setting for new Meshery installations. Use the performance.svg icon provided by https://github.com/layer5io/meshery/pull/292.

<img width="1545" alt="performance" src="https://user-images.githubusercontent.com/7570704/65555501-794c3480-def2-11e9-8ae6-6b6e980a24ae.png">

Meshery UI uses Material UI. Radio buttons are here - https://material-components.github.io/material-components-web-catalog/#/component/radio

**Additional context**
See [Load Generator Integration design doc](https://docs.google.com/document/d/1jZMOih3Qn1ixrq1Ve6fkdZZ4TuKNoF_qfClDZTnLNcw/edit#).

**Comment by leecalcote** [comment]
@cruiser1789 work is kicking off now on bringing in new a new load generator. @sakomws is working through an epic described in #126. This final issue ties off the new feature with a new UI for interacting with different load generators. Your React talents are in limited supply, so tagging you here for your consideration.

**Comment by cruiser1789** [comment]
Sure, still in a hang mode after my wife is gone, will get to this soon


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Lee Calcote <notifications@github.com> Date: 8/20/19  10:38 AM  (GMT-08:00) To: meshery/meshery <meshery@noreply.github.com> Cc: cruiser1789 <rameshtaurean@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [meshery/meshery] M4: Expose Load Generator settings in UI (#213) 
@cruiser1789 work is kicking off now on bringing in new a new load generator. @sakomws is working through an epic described in #126. This final issue ties off the new feature with a new UI for interacting with different load generators. Your React talents are in limited supply, so tagging you here for your consideration.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/meshery/meshery/issues/213?email_source=notifications\u0026email_token=AHMHCEHRFHJZJ6ALN2R4XATQFQTZ3A5CNFSM4IN2PQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4XCVVQ#issuecomment-523119318",
"url": "https://github.com/meshery/meshery/issues/213?email_source=notifications\u0026email_token=AHMHCEHRFHJZJ6ALN2R4XATQFQTZ3A5CNFSM4IN2PQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4XCVVQ#issuecomment-523119318",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by agarwalrohit2503** [comment]
@leecalcote @girishranganathan  cannot understand the issue, can you please help me understand it

**Comment by girishranganathan** [comment]
@agarwalrohit2503 this issue is dependent on https://github.com/meshery/meshery/issues/209. We should have a sync up call with @sakomws to get you to work on this.

**Comment by leecalcote** [comment]
@agarwalrohit2503 mockups have been added to this issue.

**Comment by leecalcote** [comment]
@Nikhil-Ladha can you take on the second portion (the Settings page) portion of this issue?

**Comment by Nikhil-Ladha** [comment]
@leecalcote as per the second part is concerned we already have a performance tab in the meshery page, then do we need to replicate that inside the settings section or just remove the previous one and keep this one?

**Comment by girishranganathan** [comment]
@raghavaggarwal99 I have now exposed a simple endpoint to persist load test preferences. Fetching is taking care when the page loads. You should be able to retrieve the load test preferences from redux store. Feel free to reach out to me if you have questions.
