### ISSUE TITLE
[Docs] Auto detect instruction isn't given for Minikube platform

### ISSUE THREAD

**Issue by alphaX86** [layer5io/meshery#2234]
**Current State:**
[Old] Docs mentioned that Meshery requires Docker, WSL2 and K3d cluster to start and run the app. 
[New] A pre tag is missing at last point of minikube section

**Desired State:**
Add the pre tag at last point

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by chandrashritii** [comment]
Hey @alphaX86 I'm answering this is parts :

1. Do correct me if I'm wrong here but the K3d cluster is listed as an example (to be used for this particular guide only). However, we can definitely improve the language to visibly mark it as an example and not a requirement.

2. 
> WSL2 can be run only on certain PCs and not all

 To operate correctly on Windows, Kubernetes has to run inside a Linux virtual machine. We went with WSL because it is one of the easier VM's to install and run on Windows and as far as I know (I could be wrong here, please do correct me if I am), WSL can be installed on any Windows system (having windows 7 and above) whereas WSL2 requires windows 10 (version 1903 or above). We have included instructions for both. 

3. Having a docker enabled system would be the ideal way to go as it would make the process easier on Windows but it is not in fact a requirement for running Meshery. Having either Docker or Kubernetes installed would do the job. We recommend installing Docker Desktop for Windows because it sets you up to get started with everything in a single click. I'm not sure we should remove the Docker Desktop installation step here but we could add an alternative step for users who only wish to install Kubernetes in WSL.

**Comment by alphaX86** [comment]
@chandrashritii I agree with 2 and 3. But the first point is only the doubt I have. Anyways thanks for clarify. But after reading various topics, I spotted a doc error at minikube section. I'll share the screenshot at the moment....

**Comment by alphaX86** [comment]
![Screenshot_2021-01-09-19-45-50-662_com android chrome](https://user-images.githubusercontent.com/59508546/104093881-76c24980-52b3-11eb-8c28-5fc06050e2f9.jpg)

At last part, there is no command for auto detect

**Comment by chandrashritii** [comment]
Missing tag @alphaX86 :) Thank you for pointing it out.

**Comment by alphaX86** [comment]
Sure!

**Comment by hwpplayer1** [comment]
Can we connect this issue with VS Code Atom GNU Emacs for a development environment maybe a "Milestone" is fine

**Comment by alphaX86** [comment]
> Can we connect this issue with VS Code Atom GNU Emacs for a development environment maybe a "Milestone" is fine

Could you elaborate it @hwpplayer1 ? I'd like to know it

**Comment by hwpplayer1** [comment]
> > Can we connect this issue with VS Code Atom GNU Emacs for a development environment maybe a "Milestone" is fine
> 
> Could you elaborate it @hwpplayer1 ? I'd like to know it

Like extensions both local testing, autocomplete, syntax check, all Editor features
