### ISSUE TITLE
[Docs] Add Individual doc pages for `mesheryctl` commands

### ISSUE THREAD

**Issue by alphaX86** [layer5io/meshery#2608]
**Current State:**
It's been 5 days since the `mesheryctl` command reference has got a makeover, but it's void of individual doc pages, therefore each doc page has to be created for every command so that it can be linked to the table later on. 

**Desired State:**

The reference page must be updated with links to individual doc pages. Hence, this can be a big work, and can be spliced up into smaller tasks if granted. FYI, this is Phase-2 of the makeover. 

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@alphaX86 Thanks for raising this issue. Each of the individual command pages should be autogenerated as output of a [Jekyll collection](https://jekyllrb.com/docs/collections/). Previously, I noted that the current [Jekyll datafiles](https://jekyllrb.com/docs/datafiles/) might need to be converted to a Jekyll collection in order for the pages to be automatically generated. Let's work to migrate from datafiles to a new collection, so that all of these aren't manually created.

Creation of hyperlinks to each of the automatically generated, individual command pages can also be automated and created when iterating over the collection that creates the reference table. Please do collaborate with @alonsolopezr in Slack, if you have questions or we can chat through this on the Meshery development call.

**Comment by alphaX86** [comment]
Alright @leecalcote will do as you say :) 👍

**Comment by leecalcote** [comment]
Hopefully, the migration doesn't mess with the current iteration over datafiles (it shouldn't). You can make updates to the mesheryctlcommand collection in `_config.yml` and set the `output:true` for that collection which is what will autogenerate the individual pages. You may have to add `---` to the datafiles, converting them from yaml to markdown (frontmatter).

```
---
key: value
---
```

**Comment by alphaX86** [comment]
Can we talk this during the Meshery development meet today?
