### ISSUE TITLE
[UI] User Profile menu jumping to the left in Safari

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2888]
#### Description
The user profile and its menu jumps to the left when clicked on in Safari.

#### Expected Behavior
The menu should stay in the same position.

#### Screenshots/Logs

https://user-images.githubusercontent.com/7570704/117742272-fb719580-b1c9-11eb-9fb0-03c63388d301.mov

#### Environment:
- Meshery Version: v0.5.11
- Host OS: MacOS
- Browser: Safari

**Comment by Gautam-Arora24** [comment]
I would like to take this issue 🙂

**Comment by sudo-NithishKarthik** [comment]
Hey, can I take up this issue ?

**Comment by leecalcote** [comment]
Thanks for asking, @sudo-NithishKarthik. I know that @Gautam-Arora24 has had a number of exams over the past few days, And justifiably so, has had his focus on those. I’ll let him chime in as to whether he might like to and off this issue in the meantime.

**Comment by Gautam-Arora24** [comment]
Hi @sudo-NithishKarthik! Sorry for the delay. Do you have any approach/idea on what's the bug that is causing the issue? 
I had spent few time earlier on this issue but was unable to find the bug.

**Comment by sudo-NithishKarthik** [comment]
Ya, the problem I think is because of `disablePortal` being set to `True` which always keeps the `Popper` in the `div`, and I believe that safari thinks that another element is being added to the div and it extends the width of it.  we could set `disablePortal` prop in `Popper` component to false and set the `zIndex` to be **10000**(more than that of the navigation bar) which I found to work along with setting `keepMounted` prop to `True`.

**Comment by Gautam-Arora24** [comment]
Sounds good! Go ahead. I have assigned you the issue :)

**Comment by sudo-NithishKarthik** [comment]
Sure, thank you :)
