### ISSUE TITLE
[mesheryctl] Kubernetes: `system logs` assumes Meshery Operator pod

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2911]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl` users have no way to getting logs from Meshery components deployed on Kubernetes.

#### Screenshots/Logs

```
➜  ~ mesheryctl system status
NAME                    READY   UP-TO-DATE      AVAILABLE       AGE   
meshery                 1/1     1               1               7m22s
meshery-consul          1/1     1               1               7m16s
meshery-cpx             1/1     1               1               7m12s
meshery-istio           1/1     1               1               7m19s
meshery-kuma            1/1     1               1               7m13s
meshery-linkerd         1/1     1               1               7m18s
meshery-nsm             1/1     1               1               7m15s
meshery-operator        1/1     1               1               6m58s
meshery-osm             1/1     1               1               7m10s
meshery-traefik-mesh    1/1     1               1               7m9s 
Meshery endpoint is http://localhost:9081

➜  ~ mesheryctl system logs  
Starting Meshery logging...
Error: a container name must be specified for pod meshery-operator-7f448b4fdb-hv5kq, choose one of: [kube-rbac-proxy manager]
Usage:
  mesheryctl system logs [flags]

Flags:
  -h, --help   help for logs

Global Flags:
      --config string    config file (default location is: /Users/lee/.meshery/config.yaml)
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

- Host OS: MacOS
- Meshery Version: v0.5.12
- Platform: Kubernetes (Docker Desktop)

#### Acceptance Tests
1. By default, users should see logs from Meshery Server.
2. Users should be able to specify logs from any of the other Meshery pods.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by leecalcote** [comment]
@meshery/mesheryctl-contributors

**Comment by navendu-pottekkat** [comment]
@leecalcote This is because the operator pod has 2 containers and we do not explicitly specify which container to get the logs from.

Here is the error reproduced with `kubectl`-

![Screenshot from 2021-05-13 11-51-44](https://user-images.githubusercontent.com/49474499/118086572-ce97cb00-b3e1-11eb-896e-e3f08196dcca.png)

We did not have to handle this before because all the other pods have only one container in it as shown below and only the operator pod has 2 containers-

![Screenshot from 2021-05-13 11-55-54](https://user-images.githubusercontent.com/49474499/118086914-5382e480-b3e2-11eb-907c-ed29326abd91.png)

We can fix this by forcing the logs from all the containers inside a pod. Will make a PR ASAP.

**Comment by navendu-pottekkat** [comment]
There may not be a straightforward way to do this with the client-go package. There is a workaround, but I will check if we can find another way.
