### ISSUE TITLE
[mesheryctl] `system start` and other commands fail when the version in the meshconfig is not available in GitHub

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2954]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Running `mesheryctl system start` with an invalid version(version that was not released or versions that are not yet released) in the `meshconfig` file will fail as these are not available on GitHub.

![Screenshot from 2021-05-16 22-37-10](https://user-images.githubusercontent.com/49474499/118405936-b51fa900-b697-11eb-991e-de1dc35a3951.png)

#### Desired Behavior

If the specified version is invalid, `mesheryctl` should convey that to the user and handle the error gracefully.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat does this look okay?
![image](https://user-images.githubusercontent.com/48997495/118432796-26db0f80-b6f7-11eb-8fdb-09a70dc34af9.png)

**Comment by metonymic-smokey** [comment]
Currently, version validation is done using regex. I think the approach will have to be changed, with the newer approach being fetching a list of release tags from github(using the API, similar to `GetLatestStableReleaseTag`) and checking if the version specified is part of the list.
What do you think?

**Comment by navendu-pottekkat** [comment]
Or, we could just throw an error when we try to fetch files from the invalid version. Basically just propagate the error. This will reduce the number of API calls to GitHub.

**Comment by metonymic-smokey** [comment]
> Or, we could just throw an error when we try to fetch files from the invalid version. Basically just propagate the error. This will reduce the number of API calls to GitHub.

yes, this sounds better. 
To do this, I'm checking the response status code and if it is 404, displaying a message.
![image](https://user-images.githubusercontent.com/48997495/118447638-a88a6780-b70e-11eb-8bda-036b30b61420.png)

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat is this format alright?

**Comment by leecalcote** [comment]
There's a regex in one of the commands (context?) to match against the semantic version scheme being used by the project.

**Comment by metonymic-smokey** [comment]
@leecalcote I believe you're referring to this:
https://github.com/meshery/meshery/blob/c4042fa9dc491c9882595ae8e17ba37dc3d84a17/mesheryctl/internal/cli/root/config/config.go#L84

I'm not sure this handles invalid versions which match the regex(like v0.4.200) particularly well. Only at the GET request stage will the user get a message saying it failed to make a GET request, with the usage.   
![image](https://user-images.githubusercontent.com/48997495/118779541-c7246600-b8a8-11eb-99b7-a06663fbf311.png)

That's why, in `ValidateVersion`, I want to validate the version by making a Github API call and specify that the version is not in the releases list.  I thought it would be good to do it in the beginning when checking if the current context is valid and not displaying usage since this is not related to the usage of the `mesheryctl system start` command.

**Comment by navendu-pottekkat** [comment]
Yes, the only solution here is to make the GitHub API request call. I guess we can add that check when we validate the meshconfig file

**Comment by leecalcote** [comment]
@metonymic-smokey sounds real good. Let's consolidate the version verification function to one location, if we can.

**Comment by metonymic-smokey** [comment]
@leecalcote 
Yes, that is currently happening in `ValidateVersion` in `config.go`.
