### ISSUE TITLE
Docs: Getting error 404 for overview.

### ISSUE THREAD

**Issue by Anushka-shukla** [layer5io/meshery#3023]
#### Current State
I clicked "Introducing Meshery"(https://docs.meshery.io/ ) in the QuickStart section and I'm getting error 404.
https://docs.meshery.io/overview
![WhatsApp Image 2021-05-25 at 7 42 59 PM](https://user-images.githubusercontent.com/47845585/119513154-97d29500-bd91-11eb-80e0-9dd7ee468930.jpeg)

#### Desired State
This page should open up.
![WhatsApp Image 2021-05-25 at 7 43 18 PM](https://user-images.githubusercontent.com/47845585/119513215-a4ef8400-bd91-11eb-9159-9d1145c9391b.jpeg)

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by adithyaakrishna** [comment]
@Anushka-shukla would you like to take this up?

The overview page should be this, https://web.archive.org/web/20210125092819/https://docs.meshery.io/overview

// @leecalcote @alphaX86 @Nikhil-Ladha

**Comment by Anushka-shukla** [comment]
Yes, I would like to work on this. But I'm a little confused about where to start exactly. Can you please let me know that?

**Comment by alphaX86** [comment]
@adithyaakrishna I guess that's moved to `/project` instead of `/overview`. We may have a look on this then.

If we need to change the URL then we may need to update that line.

@Anushka-shukla could you tell me how did you encounter the 404 error? I couldn't see any option `Introducing Meshery` could you send the ss of that option?

**Comment by adithyaakrishna** [comment]
@alphaX86 This link, https://docs.meshery.io/overview gives 404 Error

**Comment by Anushka-shukla** [comment]
> @adithyaakrishna I guess that's moved to `/project` instead of `/overview`. We may have a look on this then.
> 
> If we need to change the URL then we may need to update that line.
> 
> @Anushka-shukla could you tell me how did you encounter the 404 error? I couldn't see any option `Introducing Meshery` could you send the ss of that option?

https://docs.meshery.io/overview If you click this you'll get error 404.

**Comment by alphaX86** [comment]
Ah, now I get it

**Comment by adithyaakrishna** [comment]
@alphaX86 There already exists a page https://github.com/meshery/meshery/blob/master/docs/pages/getting-started/overview.md but it's not getting rendered 😶

The docs was fine at this link, https://deploy-preview-3000--meshery-docs.netlify.app/ and due to the recent restructure from PR #3010 https://deploy-preview-3010--meshery-docs.netlify.app/ there's a 404 there now

**Comment by alphaX86** [comment]
> @alphaX86 There already exists a page https://github.com/meshery/meshery/blob/master/docs/pages/getting-started/overview.md but it's not getting rendered 😶
> 
> The docs was fine at this link, https://deploy-preview-3000--meshery-docs.netlify.app/ and due to the recent restructure from PR #3010 https://deploy-preview-3010--meshery-docs.netlify.app/ there's a 404 there now

Oooooh I didn't know that actually. Hmm, in that case we may need tweaks alone. Let me check a sec about the file

**Comment by adithyaakrishna** [comment]
@alphaX86 @Anushka-shukla 

Two files need to be changes to fix this, 

- https://github.com/meshery/meshery/blob/master/docs/pages/getting-started/overview.md , In this change the line marked below to `/getting-started/overview`

![image](https://user-images.githubusercontent.com/23498248/119540322-f35d4c80-bdaa-11eb-9d03-1bfa1e5b1420.png)

- https://github.com/meshery/meshery/blob/master/docs/pages/index.md , In this change the line marked to `/getting-started/overview`

![image](https://user-images.githubusercontent.com/23498248/119540495-20116400-bdab-11eb-98af-be5c426b5135.png)

@Anushka-shukla If these are done, this issue should be fixed with the above changes. Happy Hacking 🚀

**Comment by Anushka-shukla** [comment]
> @alphaX86 @Anushka-shukla
> 
> Two files need to be changes to fix this,
> 
> * https://github.com/meshery/meshery/blob/master/docs/pages/getting-started/overview.md , In this change the line marked below to `/getting-started/overview`
> 
> ![image](https://user-images.githubusercontent.com/23498248/119540322-f35d4c80-bdaa-11eb-9d03-1bfa1e5b1420.png)
> 
> * https://github.com/meshery/meshery/blob/master/docs/pages/index.md , In this change the line marked to `/getting-started/overview`
> 
> ![image](https://user-images.githubusercontent.com/23498248/119540495-20116400-bdab-11eb-98af-be5c426b5135.png)
> 
> @Anushka-shukla If these are done, this issue should be fixed with the above changes. Happy Hacking

Okay I'll do!
