### ISSUE TITLE
Improve the custom 404 page in Meshery docs

### ISSUE THREAD

**Issue by l5io** [layer5io/meshery#345]
It would be nice if the [custom 404 page](docs/404.html) in Meshery docs included a bit of related humor like: 

- "Oh, no. Please pardon our meshy site."
- "Oops. Please excuse the mesh."

**Comment by firstladymb** [comment]
Is there anything left to do for this? Looks completed!

**Comment by leecalcote** [comment]
@firstladymb, yes, you're right in that this issue was fixed as described. It's been left open as a reminder that an enhancement here is desired.

At the same time that this issue was opened, so too was [an issue opened](https://github.com/layer5io/layer5/issues/200) on the Meshery project's [sister Jekyll site](https://github.com/layer5io/layer5) at https://layer5.io. 

The solution provided for that issue included [a simple random message loader](https://github.com/layer5io/layer5/pull/204/files), which we are hopeful someone will copy/recreate within the Meshery project's docs. 

If you're inclined, your assistance here would be warmly welcomed. :)

**Comment by firstladymb** [comment]
I'll take it! I have a branch with the changes and I'm looking into how to prevent the header links and TOC from being automatically created.
