### ISSUE TITLE
Add more documentation on the steps in the Makefile like `make docker`

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery#352]
**Enhancement Description**
It will be helpful to the contributors if the `Makefile` has a little more documentation around the different steps so that they are informed of what is really happening when they execute each `make` command.

**Comment by leecalcote** [comment]
@girishranganathan thank you! @mcastre as you go through this, I wonder if your notes on the subject might not make for a great update to the comments in the file.

**Comment by mcastre** [comment]
After running `make docker` cmd, Docker built the image successfully. I couldn't figure out what the next docker cmd was to run the image. @girishranganathan told me to run the normal `make run-local` cmd to start up the server and that worked. I was able to run the UI and the server. 

However, i did notice that when i ran `docker ps`, the new image was not running. The first time i got docker running was by following the instruction in the docs on the website:
```
sudo curl -L https://git.io/meshery -o /usr/local/bin/meshery;
sudo chmod a+x /usr/local/bin/meshery; 
meshery start
```

**Comment by leecalcote** [comment]
@mcastre callouts here. The intention is for the three lines of command line above to be executed in order to run Meshery, while the Makefile be executed in order to build Meshery. Given that you've done both a number of times now, I wonder if you consider that either needs updated / improved. All suggestions welcome. :)
