### ISSUE TITLE
Strip off /graph from grafana and prometheus endpoint

### ISSUE THREAD

**Issue by subhamkrai** [layer5io/meshery#612]
Strip off any extraneous portion of the URL beyond the port number (e.g. http://kubernetes.docker.internal:32291/graph ) strip off /graph of both Prometheus and grafana connection endpoint.

**Comment by girishranganathan** [comment]
@subhamkrai responding to your slack message here so that you will have a relevant record:
there are 2 ways you can tackle this issue.
in the UI or in the backend
i will say just do it in the backend handler
there is one for prometheus and one for grafana
you just need to add a check to see if the URL ends with /graph and if it does, remove it

feel free to reach out if you have any questions

**Comment by subhamkrai** [comment]
Sure I'll

**Comment by leecalcote** [comment]
@subhamkrai this issue still seems to remain with Prometheus endpoints. When I enter `http://x.x.x.x:port-number/graph`, this error occurs:

```
meshery_1           | time="2020-04-19T05:38:11Z" level=error msg="unable to get data from URL: http://192.168.1.15:30168/graph/api/v1/status/config due to status code: 404"
meshery_1           | time="2020-04-19T05:38:11Z" level=error msg="unable to connect to prometheus: unable to fetch data from url: http://192.168.1.15:30168/graph/api/v1/status/config"
```

However, when I enter `http://x.x.x.x:port-number`, the connection is made without issue. Will you investigate?

**Comment by leecalcote** [comment]
@subhamkrai here's an example from v0.3.18:

![Untitled](https://user-images.githubusercontent.com/7570704/86525594-be70a000-be4e-11ea-9b5e-960f06f9ebde.gif)

@Nikhil-Ladha recently provided a fix for reloading component data.

**Comment by leecalcote** [comment]
@subhamkrai did we ever confirm that the issue shown this this screen capture is fixed?
