### ISSUE TITLE
Docs: Convert adapters collection to data file

### ISSUE THREAD

**Issue by schillingjerrid** [layer5io/meshery#654]
**Current State:**
The list of adapters for the docs site is currently housed in a [collection](https://jekyllrb.com/docs/collections/).

**Desired State:**
* Move the adapters to a [data file](https://jekyllrb.com/docs/datafiles/).
* Update all of the references to the adapters to use the newly added data file.

Required fields are (not limited to):
* title
* name
* version
* port
* project_status

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by schillingjerrid** [comment]
@leecalcote I didn't see an issue for this and I remember we talked about it a while ago. Is there anything you'd like me to change with the wording or the fields to include?

**Comment by leecalcote** [comment]
@schillingjerrid thank you for getting this issue filed. 😄 Yes, please fire away on this. Here's a good example of the fields needed:

```
long-name: Meshery Adapter for Consul
short-name: Consul
sm-version:  v1.5
adapter-version:
adapter-port: 10002/tcp
adapter-status: stable
```

**Comment by schillingjerrid** [comment]
@leecalcote That sounds good to me. I'll get on it.

**Comment by schillingjerrid** [comment]
@leecalcote How do we want to handle displaying data for each adapter? Currently each adapter links to another page that will show information specific to the selected adapter. Most of the pages are empty at this point but the Octarine adapter page is filled out with information.

Also do we want to retain the Octarine information in some way?

**Comment by leecalcote** [comment]
@schillingjerrid great questions. 
- We do want to retain individual pages for details specific to each adapter. Instead of the adapter's metadata being stored in front matter in each page, each page will capture architecture, usage and so on for each adapter. While the data file will capture the succinct details about each adapter in one place.
- Yes, we do want to retain the Octarine adapter information.

As we convert from a collection to a data file, we may find that some of the benefits in doing so are something of a wash between the two approaches (a collection or a data file). I think what propels us forward toward a data file approach being the slightly better approach is the notion that this same data file can be replicated across the layer5.io/landscape, the docs.meshery.io and the meshery.io sites. This file - 
[service-meshes.yml.txt](https://github.com/layer5io/meshery/files/4242281/non-functional.yml.txt) - might make for a good universal data file across these three sites.

**Comment by leecalcote** [comment]
@rootsongjc, SOFAmesh is an inactive project while MOSN is an active project, right?

**Comment by rootsongjc** [comment]
@leecalcote Yes, SOFAMesh is a project that forked from Istio. And now it has stopped developing in this way. The SOFAMesh team is contributing to Istio directly. So you can remove it from the list.

**Comment by schillingjerrid** [comment]
That sounds good. I will add it as a sub task of this issue.

**Comment by leecalcote** [comment]
@schillingjerrid we've made some recent updates to the [Meshery readme](https://github.com/layer5io/meshery/blob/master/README.md) file. As you have a look, I'm curious for your opinion on whether you think a table (or list) of Meshery's adapters in that readme would benefit the project / would-be users or not.

**Comment by leecalcote** [comment]
Good to go here. We finally converted to a collection.
